In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
a2 = np.array([[1,2,3], [2,3,4]])
a2

array([[1, 2, 3],
       [2, 3, 4]])

In [5]:
a1.ndim, a2.ndim

(1, 2)

In [6]:
a1.dtype, a2.dtype

(dtype('int64'), dtype('int64'))

In [7]:
a1.size, a2.size

(3, 6)

In [9]:
type(a1), type(a2)

(numpy.ndarray, numpy.ndarray)

In [12]:
ones = np.ones((2,3), dtype=float)
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
zeroes = np.zeros((2,3), dtype=int)
zeroes

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
range_array = np.arange(0, 20, 2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[0, 3, 0, 2, 0],
       [5, 4, 2, 9, 6],
       [7, 3, 2, 7, 1]])

In [19]:
random_array_2 = np.random.random((3,5))
random_array_2

array([[0.44408281, 0.56604883, 0.09743297, 0.77982423, 0.10673696],
       [0.11613276, 0.67921671, 0.37303541, 0.60384595, 0.70609466],
       [0.39816122, 0.93300443, 0.13342339, 0.71667417, 0.5326625 ]])

In [20]:
random_array_3 = np.random.rand(5,3,2)
random_array_3

array([[[0.40824762, 0.43674225],
        [0.76655955, 0.84707226],
        [0.86695488, 0.59803199]],

       [[0.42459048, 0.33615322],
        [0.01545999, 0.92845945],
        [0.99282705, 0.27620387]],

       [[0.62617528, 0.59651868],
        [0.95189881, 0.11596202],
        [0.11596082, 0.63708759]],

       [[0.45338348, 0.24938617],
        [0.18203608, 0.37926166],
        [0.01738815, 0.98751278]],

       [[0.2802039 , 0.4726637 ],
        [0.22301991, 0.01821133],
        [0.15341514, 0.0027911 ]]])

In [45]:
np.random.seed(3)
random_array_2 = np.random.random((3,5))
random_array_2

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695],
       [0.89629309, 0.12558531, 0.20724288, 0.0514672 , 0.44080984],
       [0.02987621, 0.45683322, 0.64914405, 0.27848728, 0.6762549 ]])

In [46]:
np.unique(np.array([1,2,2,1,3,4,4,5]))

array([1, 2, 3, 4, 5])

In [47]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[2, 1, 3, 5, 8],
         [1, 8, 7, 8, 1],
         [0, 5, 4, 1, 5],
         [4, 7, 6, 0, 0]],

        [[9, 2, 4, 5, 8],
         [8, 7, 5, 1, 1],
         [1, 5, 5, 7, 4],
         [3, 0, 0, 0, 0]],

        [[2, 2, 7, 0, 5],
         [0, 1, 4, 1, 2],
         [2, 4, 8, 0, 6],
         [0, 4, 1, 5, 1]]],


       [[[8, 8, 7, 0, 0],
         [9, 1, 7, 8, 7],
         [4, 0, 0, 4, 3],
         [0, 8, 2, 7, 2]],

        [[1, 3, 2, 4, 1],
         [2, 2, 7, 3, 4],
         [1, 6, 7, 9, 1],
         [0, 0, 5, 8, 4]],

        [[8, 8, 3, 4, 9],
         [2, 5, 4, 7, 9],
         [1, 9, 0, 7, 4],
         [8, 8, 4, 1, 4]]]])

In [62]:
a4[1][1][1]

array([2, 2, 7, 3, 4])

In [66]:
massive_array = np.random.random(100000)

In [67]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

6.63 ms ± 169 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
35.2 μs ± 3.84 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
